"use client";
import { useState, useEffect } from "react";
import { supabase } from "@/lib/supabaseClient";
import TimeAgo from "./TimeAgo"; // Pastikan file ini ada

export default function PostCard({ id, content, author, votes, image_url, created_at, myName, onUserClick }) {
  const [likeCount, setLikeCount] = useState(votes || 0);
  const [hasLiked, setHasLiked] = useState(false); // Simulasi local state (ideal: cek DB)
  
  // State Komentar
  const [showComments, setShowComments] = useState(false);
  const [comments, setComments] = useState([]);
  const [newComment, setNewComment] = useState("");
  const [commentCount, setCommentCount] = useState(0);

  // --- 1. LOGIC LIKE & NOTIFIKASI ---
  const handleVote = async () => {
    // Optimistic Update
    const newCount = hasLiked ? likeCount - 1 : likeCount + 1;
    setLikeCount(newCount);
    setHasLiked(!hasLiked);

    // Update DB
    await supabase.from("posts").update({ votes: newCount }).eq("id", id);

    // Kirim Notifikasi (Hanya kalau Like, bukan Unlike)
    if (!hasLiked && author !== myName) {
        await supabase.from("notifications").insert([{
            recipient: author,
            actor: myName,
            type: 'like',
            content: content.substring(0, 30) + (content.length > 30 ? "..." : ""),
            is_read: false
        }]);
    }
  };

  // --- 2. LOGIC KOMENTAR ---
  const fetchComments = async () => {
      // Ambil komentar real dari DB (kita butuh tabel comments, kalau belum ada pakai array dummy dulu atau buat tabel)
      // DISINI KITA SIMULASI SEDERHANA MENGGUNAKAN TABEL 'comments'
      // Pastikan tabel 'comments' ada. Kalau belum, buat tabel:
      /* create table comments (
           id bigint generated by default as identity primary key,
           post_id bigint not null,
           author text not null,
           content text not null,
           created_at timestamp with time zone default now()
         );
      */
      
      const { data, count } = await supabase
        .from("comments")
        .select("*", { count: "exact" })
        .eq("post_id", id)
        .order("created_at", { ascending: true });
        
      if (data) setComments(data);
      if (count !== null) setCommentCount(count);
  };

  const toggleComments = () => {
      setShowComments(!showComments);
      if (!showComments) fetchComments();
  };

  const handleSendComment = async (e) => {
      e.preventDefault();
      if (!newComment.trim()) return;

      // Optimistic
      const tempComment = {
          id: Math.random(),
          post_id: id,
          author: myName,
          content: newComment,
          created_at: new Date().toISOString()
      };
      setComments([...comments, tempComment]);
      setNewComment("");
      setCommentCount(commentCount + 1);

      // Insert DB
      await supabase.from("comments").insert([{
          post_id: id,
          author: myName,
          content: tempComment.content
      }]);

      // Kirim Notifikasi
      if (author !== myName) {
          await supabase.from("notifications").insert([{
            recipient: author,
            actor: myName,
            type: 'comment',
            content: tempComment.content,
            is_read: false
        }]);
      }
  };

  // Cek jumlah komen saat pertama load (count only)
  useEffect(() => {
      const getCount = async () => {
          const { count } = await supabase.from("comments").select("*", { count: 'exact', head: true }).eq("post_id", id);
          if (count) setCommentCount(count);
      };
      getCount();
  }, [id]);

  return (
    <div className="bg-white p-5 rounded-3xl shadow-sm border border-gray-100 mb-4 hover:shadow-md transition animate-in fade-in">
      
      {/* HEADER: Avatar & Nama */}
      <div className="flex items-center gap-3 mb-3">
        <img 
            src={`https://api.dicebear.com/9.x/notionists/svg?seed=${author}`} 
            alt="avatar" 
            className="w-10 h-10 rounded-full border border-gray-100 bg-gray-50 cursor-pointer hover:opacity-80 transition"
            onClick={() => onUserClick && onUserClick(author)}
        />
        <div>
            <h4 
                className="font-bold text-gray-800 text-sm cursor-pointer hover:text-green-600 transition"
                onClick={() => onUserClick && onUserClick(author)}
            >
                @{author}
            </h4>
            <TimeAgo timestamp={created_at} />
        </div>
      </div>

      {/* CONTENT: Teks & Gambar */}
      <p className="text-gray-700 text-sm leading-relaxed mb-3 whitespace-pre-wrap">{content}</p>
      
      {image_url && (
          <div className="mb-4 rounded-2xl overflow-hidden border border-gray-100">
              <img src={image_url} alt="Post image" className="w-full h-auto object-cover max-h-[400px]" />
          </div>
      )}

      {/* FOOTER: Tombol Aksi */}
      <div className="flex items-center gap-6 pt-3 border-t border-gray-50">
          {/* Tombol Like */}
          <button 
            onClick={handleVote}
            className={`flex items-center gap-2 text-sm font-bold transition ${hasLiked ? "text-pink-500" : "text-gray-400 hover:text-pink-400"}`}
          >
              <span className="text-lg">{hasLiked ? "❤️" : "🤍"}</span>
              {likeCount > 0 && <span>{likeCount}</span>}
          </button>

          {/* Tombol Komen */}
          <button 
            onClick={toggleComments}
            className="flex items-center gap-2 text-sm font-bold text-gray-400 hover:text-blue-500 transition"
          >
              <span className="text-lg">💬</span>
              {commentCount > 0 && <span>{commentCount}</span>}
          </button>
      </div>

      {/* SECTION KOMENTAR (Accordion) */}
      {showComments && (
          <div className="mt-4 pt-4 border-t border-gray-50 animate-in slide-in-from-top-2">
              <div className="space-y-3 mb-4 max-h-60 overflow-y-auto custom-scrollbar pr-2">
                  {comments.length === 0 ? (
                      <p className="text-center text-xs text-gray-400 py-2">Belum ada komentar.</p>
                  ) : (
                      comments.map((c, idx) => (
                          <div key={idx} className="flex gap-2 text-sm">
                              <span className="font-bold text-gray-700 text-xs">@{c.author}</span>
                              <p className="text-gray-600 text-xs">{c.content}</p>
                          </div>
                      ))
                  )}
              </div>

              {/* Input Komentar */}
              <form onSubmit={handleSendComment} className="flex gap-2">
                  <input 
                    value={newComment}
                    onChange={(e) => setNewComment(e.target.value)}
                    className="flex-1 bg-gray-50 border border-gray-100 rounded-xl px-3 py-2 text-xs focus:outline-none focus:ring-1 focus:ring-blue-200"
                    placeholder="Tulis balasan..."
                  />
                  <button type="submit" disabled={!newComment.trim()} className="text-blue-500 font-bold text-xs px-2 hover:bg-blue-50 rounded-lg transition">
                      Kirim
                  </button>
              </form>
          </div>
      )}

    </div>
  );
}